---
title: "LDA"
author: "Igor Adamiec"
date: "1/22/2019"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
dataset <- read_csv("Wine.csv")
```
```{r}
library(caTools)
set.seed(123)
split <- sample.split(dataset$Customer_Segment, SplitRatio = .8)
training_set <- dataset %>%
  subset(split == T)
test_set <- dataset %>% 
  subset(split == F)
```

```{r}
training_set[-14] <- scale(training_set[-14])
test_set[-14] <- scale(test_set[-14])
```

```{r}
library(MASS)
library(dplyr)
```
```{r}
lda <- lda(formula = Customer_Segment ~ .,
           data = training_set)
```
```{r}
lda_train_set <- predict(lda,
                         training_set) %>% 
  as.data.frame()
lda_train_set <- lda_train_set[c(5, 6, 1)]
```
```{r}
lda_test_set <- predict(lda,
                         test_set) %>% 
  as.data.frame()
lda_test_set <- lda_test_set[c(5, 6, 1)]
```

```{r}
library(e1071)
classifier <- svm(formula = class ~., 
                  data = lda_train_set,
                  type = "C-classification",
                  kernel = "linear")
```

```{r}
y_pred <- predict(classifier, newdata = lda_test_set[-3])
```

```{r}
table(lda_test_set[,3], y_pred)
```

```{r}
set = lda_train_set
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('x.LD1', 'x.LD2')
y_grid = predict(classifier, newdata = grid_set)
plot(set[, -3],
     main = 'Classifier (Training set)',
     xlab = 'LD1', ylab = 'LD2',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'springgreen3', ifelse(y_grid == 2, 'firebrick2', 'deepskyblue3')))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'green4', ifelse(set[, 3] == 2, 'red3', 'blue3')))
```
```{r}
set = lda_test_set
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('x.LD1', 'x.LD2')
y_grid = predict(classifier, newdata = grid_set)
plot(set[, -3],
     main = 'Classifier (Test set)',
     xlab = 'LD1', ylab = 'LD2',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'springgreen3', ifelse(y_grid == 2, 'firebrick2', 'deepskyblue3')))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'green4', ifelse(set[, 3] == 2, 'red3', 'blue3')))
```