---
title: "Simple Linear Regression"
author: "Igor Adamiec"
date: "12/21/2018"
output: html_document
---

```{r}
library(tidyverse)
salary <- read_csv("Salary_Data.csv")
```

```{r}
ggplot(data = salary, aes(x = YearsExperience, y = Salary)) + geom_point()
```

```{r}
library(caTools)
set.seed(123)
split <- sample.split(salary$Salary, SplitRatio = 2/3)
training_set <- salary %>% 
  subset(split == T)

test_set <- salary %>% 
  subset(split == F)
```

LR package does scaling

```{r}
regressor <- lm(formula = Salary ~ YearsExperience, data = training_set)
summary(regressor)
```

```{r}
y_pred <- predict(regressor, newdata = test_set)
```

# Train data visualisation
```{r}
ggplot(data = training_set, aes(x = training_set$YearsExperience, y = training_set$Salary)) +
  geom_point(colour = 'red') +
   geom_line(aes(x = training_set$YearsExperience, y = predict(regressor, newdata = training_set)),
               colour = 'blue') + 
    geom_smooth(method = 'lm') +
    ggtitle('Salary vs Experience (Training set)') +
    xlab('Years of experience') +
    ylab('Salary')
```


#Test set visualisation
```{r}
ggplot()+
  geom_point(aes(x = test_set$YearsExperience, y = test_set$Salary),
             color = "red") +
  geom_line(aes(x = training_set$YearsExperience, y = predict(regressor,newdata = training_set)),
            color = "blue") 
```



