---
title: "Kernel PCA"
author: "Igor Adamiec"
date: "1/23/2019"
output: html_document
---

```{r}
library(tidyverse)
library(caTools)
```
```{r}
dataset <- read_csv("Social_Network_Ads.csv") %>% 
  select(-'User ID', - Gender) %>% 
  mutate(Purchased = as.factor(Purchased)) 
```
```{r}
head(dataset)
```
```{r}
glimpse(dataset)
```

```{r}
set.seed(123)
split <- sample.split(dataset$Purchased, SplitRatio = .75)
training_set <- subset(dataset, split == T) %>% 
  mutate_if(is.double, scale) %>% 
  mutate_if(is.matrix, as.numeric)
test_set <- subset(dataset, split == F) %>% 
  mutate_if(is.double, scale)%>% 
  mutate_if(is.matrix, as.numeric)
```

#Kernel PCA
```{r}
library(kernlab)
```
```{r}
kpca <- kpca(~.,
             data = training_set %>% select(-Purchased),
             kernel = "rbfdot",
             features = 2)
```

```{r}
kpca_train_set <- predict(kpca, training_set) %>% 
  as.data.frame()
```

```{r}
kpca_train_set <- kpca_train_set %>% 
  bind_cols(training_set %>% select(Purchased))
```

```{r}
kpca_test_set <- predict(kpca, test_set) %>% 
  as.data.frame()
```

```{r}
kpca_test_set <- kpca_test_set %>% 
  bind_cols(test_set %>% select(Purchased))
```

#Logistic regression

```{r}
classifier <- glm(formula = Purchased ~., 
                  data = kpca_train_set,
                  family = binomial)
summary(classifier)
```

```{r}
prob_pred <- predict(classifier, type = 'response', newdata = kpca_test_set %>% select(-Purchased))
```

```{r}
y_pred <- ifelse(prob_pred > .5, 1, 0)
```

```{r}
cm = table(kpca_test_set %>% pull(Purchased), y_pred)
cm
```

```{r}
library(ElemStatLearn)
```
```{r}

```

```{r}
set = kpca_train_set
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('V1', 'V2')
y_grid = predict(classifier, newdata = grid_set, type = 'response')
y_grid <- ifelse(y_grid > .5, 1, 0)
plot(set[, -3],
     main = 'Kernel PCA (Training set)',
     xlab = 'V1', ylab = 'V2',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'springgreen3', 'tomato'))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'green4', 'red3'))
```
```{r}
ggplot()+
  geom_point(data = grid_set, aes(x = V1, y = V2), color = ifelse(y_grid == 1, 'springgreen3', 'tomato'))+
  geom_point(data = set, aes(x = V1, y = V2), pch = 21, fill = ifelse(set$Purchased == 1,  'green4', 'red3'), color = "black")+
  labs(title = "Kernel PCA + Logistic Regression on training set", x = "V1", y = "V2")
  
```

```{r}
ggplot()+
  geom_point(data = grid_set, aes(x = V1, y = V2), color = ifelse(y_grid == 1, 'springgreen3', 'tomato'))+
  geom_point(data = kpca_test_set, aes(x = V1, y = V2), pch = 21, fill = ifelse(test_set$Purchased == 1,  'green4', 'red3'), color = "black")+
  labs(title = "Kernel PCA + Logistic Regression on test set", x = "V1", y = "V2")
  
```


