---
title: "Data Preprocessing"
author: "Igor Adamiec"
date: "12/21/2018"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
ds <- read_csv(file = "Data.csv")
```

```{r}
ds %>% View()
```

```{r}
glimpse(ds)
```
```{r}
summary(ds)
```

# Categorical Data

```{r}
ds_factored <- ds %>% 
  mutate(Country = factor(Country, 
                          levels = c("France", "Spain", "Germany"), 
                          labels = c(1, 2, 3)),
         Purchased = factor(Purchased,
                            levels = c("No", "Yes"),
                            labels = c(0, 1)))
```

```{r}
glimpse(ds)
```

# Missing data

```{r}
ds_missing <- ds_factored %>% 
  mutate(Age = ifelse(is.na(Age), 
                      mean(Age, na.rm = T), 
                      Age),
         Salary = ifelse(is.na(Salary),
                         mean(Salary, na.rm = T),
                         Salary))

ds_missing
```

# Spliting the dataset into training and testing
```{r}
library(caTools)
```

```{r}
set.seed(123)
```

```{r}
split <- sample.split(ds_missing$Purchased,
                      SplitRatio = .8)
```

```{r}
training_set <- subset(ds_missing, split == T)
test_set <- subset(ds_missing, split == F)

glimpse(test_set)
```

# Scaling
```{r}
training_set <- training_set %>% 
  mutate_if(is.double, scale)

test_set <- test_set %>% 
  mutate_if(is.double, scale)
```

