---
title: "Thompson Sampling"
author: "Igor Adamiec"
date: "1/11/2019"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
dataset <- read_csv("Ads_CTR_Optimisation.csv")
```

```{r}
N <- 10000
d <- 10
ads_selected <- integer(0)
total_reward <- 0
numbers_of_rewards_1 <- integer(d)
numbers_of_rewards_0 <- integer(d)
for (n in 1:N) {
  ad <- 0
  max_random <- 0
  for (i in 1:d) {
    random_beta <- rbeta(n = 1,
                         shape1 = numbers_of_rewards_1[i] + 1,
                         shape2 = numbers_of_rewards_0[i] + 1)
    if (random_beta > max_random) {
      max_random <- random_beta
      ad <- i
    }
  }
  ads_selected <- append(ads_selected, ad)
  reward <- dataset[n, ad] %>% pull()
  if (reward == 1) {
    numbers_of_rewards_1[ad] <- numbers_of_rewards_1[ad] + 1
  } else {
    numbers_of_rewards_0[ad] <- numbers_of_rewards_0[ad] + 1
  }
  total_reward <- total_reward + reward
}
```

```{r}
ggplot()+
  geom_col(aes(x = 1:10, y = numbers_of_rewards_1), fill = "deepskyblue4") +
  scale_x_continuous(breaks = 1:10) +
  labs(title = "Number of rewards 1 of every ad",
       x = "Ads", y = "Rewards 1") +
  theme(plot.title = element_text(hjust = .5),
        plot.background = element_rect(fill = "lightblue2"),
        panel.background = element_rect(fill = "lightblue2"))
```

```{r}
ggplot()+
  geom_col(aes(x = 1:10, y = numbers_of_rewards_0), fill = "deepskyblue4") +
  scale_x_continuous(breaks = 1:10) +
  labs(title = "Number of rewards 0 of every ad",
       x = "Ads", y = "Rewards 0") +
  theme(plot.title = element_text(hjust = .5),
        plot.background = element_rect(fill = "lightblue2"),
        panel.background = element_rect(fill = "lightblue2"))
```