---
title: "K-Means"
author: "Igor Adamiec"
date: "1/4/2019"
output: html_document
---

```{r}
library(tidyverse)
library(broom)
```
```{r}
dataset <- read_csv("Mall_Customers.csv")
```

```{r}
X <- dataset %>% 
  select(`Annual Income (k$)`, `Spending Score (1-100)`)
```



```{r}
set.seed(29)
kmeans <- kmeans(X, 
                 centers = 5,
                 iter.max = 300,
                 nstart = 10)
```

```{r}
ggplot() +
  geom_point(data = X, aes(x = `Annual Income (k$)`, y = `Spending Score (1-100)`))
```

```{r}

ggplot(data = augment(kmeans, X)) +
  geom_point(aes(x = `Annual.Income..k..`, y = `Spending.Score..1.100.`, color = .cluster)) +
  stat_ellipse(aes(x = `Annual.Income..k..`, y = `Spending.Score..1.100.`,  fill = .cluster),
               geom = "polygon", alpha = .2)+
  labs(title = "Clusters",
       x = "Annual Income",
       y = "Spending Score") +
  theme(plot.title = element_text(hjust = .5))+
  guides(color = guide_legend("Cluster"), fill = guide_legend("Cluster"))
```

```{r}
tidy(kmeans)
```

```{r}
glance(kmeans)
```



```{r}
set.seed(6)
kclusts <- tibble(k = 1:10) %>% 
  mutate(kclust = map(k, ~kmeans(X, .x)),
         tidied = map(kclust, tidy),
         glanced = map(kclust, glance),
         augmented = map(kclust, augment, X))
```

```{r}
clustering <- kclusts %>% 
  unnest(glanced)

ggplot(data = clustering) +
  geom_line(aes(x = k, y = tot.withinss)) +
  geom_point(aes(x = k, y = tot.withinss), color = "blue") +
  labs(title = "The Elbow method",
       x = "Number of clusters",
       y ="WCSS") +
  scale_y_continuous(labels = scales::comma, breaks = seq(50000, 350000, by = 50000)) +
  scale_x_continuous(breaks = seq(2,10, by = 2)) +
  theme(plot.title = element_text(hjust = .5),
        panel.grid.major.y = element_line(color = "grey"),
        panel.grid.minor.y = element_line(color = "grey"))
```

```{r}
assignemnts <- kclusts %>% 
  unnest(augmented) %>% 
  rename(x1 = Annual.Income..k..,
         x2 = Spending.Score..1.100.) %>% 
  mutate(.cluster = as.factor(as.numeric(.cluster)))
assignemnts
```
```{r}
p1 <- ggplot(data = assignemnts, aes(x = x1, y = x2)) +
  geom_point(aes(color = .cluster)) +
  facet_wrap(~k)+
  labs(title = "Clusters",
       x = "Annual Income",
       y = "Spending Score") +
  theme(plot.title = element_text(hjust = .5))+
  scale_color_discrete(name = "Clusters" )
p1
```
```{r}
clusters <- kclusts %>% 
  unnest(tidied)
p1 +
  geom_point(data = clusters, shape = "x", size = 5)+
  labs(title = "Culsters' centers")
```

