---
title: "PCA"
author: "Igor Adamiec"
date: "1/21/2019"
output: html_document
---

```{r}
library(tidyverse)
```
```{r}
dataset <- read_csv("Wine.csv")
```
```{r}
dataset %>% head %>% group_by(Alcohol)
```

```{r}
dataset %>% glimpse
```

```{r}
library(caTools)
set.seed(123)
split <- sample.split(dataset$Customer_Segment, SplitRatio = .8)
training_set <- dataset %>%
  subset(split == T)
test_set <- dataset %>% 
  subset(split == F)
```

```{r}
training_set[-14] <- scale(training_set[-14])
test_set[-14] <- scale(test_set[-14])
```

```{r}
library(caret)
library(e1071)
```
```{r}
pca <- preProcess(x = training_set[-14],
                  method = "pca",
                  pcaComp = 2)
```

```{r}
pca_train_set <- predict(pca, training_set) %>% 
  select(PC1, PC2, Customer_Segment)
```

```{r}
pca_test_set <- predict(pca, test_set) %>% 
  select(PC1, PC2, Customer_Segment)
```

```{r}
classifier <- svm(formula = Customer_Segment ~., 
                  data = pca_train_set,
                  type = "C-classification",
                  kernel = "linear")
```

```{r}
y_pred <- predict(classifier, newdata = pca_test_set[-3])
```

```{r}
table(pca_test_set[,3], y_pred)
```

```{r}
set = pca_train_set
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('PC1', 'PC2')
y_grid = predict(classifier, newdata = grid_set)
plot(set[, -3],
     main = 'Classifier (Training set)',
     xlab = 'PC1', ylab = 'PC2',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'springgreen3', ifelse(y_grid == 2, 'red3', 'blue3')))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'green4', ifelse(set[, 3] == 2, 'red3', 'blue3')))
```

```{r}
set = pca_test_set
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('PC1', 'PC2')
y_grid = predict(classifier, newdata = grid_set)
plot(set[, -3],
     main = 'Classifier (Training set)',
     xlab = 'PC1', ylab = 'PC2',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'springgreen3', ifelse(y_grid == 2, 'firebrick1', 'deepskyblue')))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'green4', ifelse(set[, 3] == 2, 'red4', 'blue4')))
```
