---
title: "drugie"
author: "Igor Adamiec"
date: "24 08 2019"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
df <- read_csv("./zapis_full.csv")
```

```{r}
df_unnested <- df %>% 
  select(-L.p.) %>% 
  rename("pojazd"= "Rodzaj statku powietrznego",
         "trasa" = "Trasa przelotu") %>% 
  mutate(pojazd = str_trim(pojazd, side = "both"),
         Termin = str_trim(Termin, side = "both"),
         trasa = str_trim(trasa, side = "both"),
         trasa = str_split(trasa, pattern = "-")) %>% 
  unnest 
  
```

```{r}
df_v1 <- df_unnested %>% 
  mutate(
    trasa = str_trim(trasa, side = "both"),
    trasa = case_when(trasa == "Rzym" ~ "LIRF",
                           trasa == "Berlin" ~ "EDDT",
                           trasa == "Paryż" ~ "LFPG",
                           trasa == "Bruksela" ~ "EBBR",
                           trasa == "Irak"~ "ORBI",
                           trasa == "Moskwa" ~ "UUEE",
                           trasa == "Świdwin" ~ "EPSE",
                           trasa == "Kijów" ~ "UKBB",
                           trasa == "Lima" ~ "SPIM",
                           trasa == "Santiago de Chile" ~ "SCEL",
                           trasa == "Nowy Targ" ~ "EPNT",
                           trasa == "Gołdap" ~"EPWA",
                           trasa == "Krynica (Krzyżówka)" ~ "EPGD",
                           trasa == "Sztokcholm" ~ "ESSA",
                      trasa == "Strzelce Op." ~ "EPOP",
                      trasa == "Sewilla"~ "LEZL",
                      trasa == "WAW" ~ "EPWA",
                      trasa == "Szanghaj" ~ "ZSPD",
                      trasa == "Pekin" ~ "ZBAA",
                      trasa == "Frankfurt" ~ "EDDF",
                      trasa == "Kuwejt" ~ "OKBK",
                      trasa == "Londyn" ~ "EGLL",
                      trasa == "Radzikowo" ~ "EPSK",
                      trasa == "Werona" ~ "LIPX",
                      trasa == "Bratysława" ~ "LZIB",
                      trasa == "Zurich" ~ "LSZH",
                      trasa == "Monachium" ~ "EDDM",
                      trasa == "Hamburg" ~ "EDDH",
                      trasa == "Radom" ~ "EPRA",
                      trasa == "Olecko" ~ "EPSY",
                      trasa == "Praga" ~ "LKPR",
                      trasa == "Tallin" ~ "EETN",
                      trasa == "Helsinki" ~ "EFHK",
                      trasa == "Kazimierz Biskupi" ~ "EPKB",
                      trasa == "Poniatowa" ~ "LUZ",
                      trasa == "Turbia" ~ "EPST",
                      trasa == "Rzeszów" ~ "EPRZ",
                      trasa == "Pomysk Wlk." ~ "NA",
                      trasa == "Osnabruck" ~ "EDWO",
                      trasa == "Jarocin" ~ "NA",
                      trasa == "Eindhoven" ~ "EHEH",
                      trasa == "Valetta" ~"LMML",
                      trasa == "Ateny" ~ "LGAV",
                      trasa == "Kolonia" ~ "EDDK",
                      trasa == "Kopenhaga" ~ "EKCH",
                      trasa == "Orzysz" ~ "PL-0058",
                      trasa == "Oświęcim" ~"EPKK",
                      trasa == "BUD" ~"LHBP",
                      trasa == "Gdynia" ~ "EPOK",
                      trasa == "Tbilisi" ~ "UGTB",
                      trasa == "Smoleńsk" ~ "RU-4069",
                      trasa == "Erewań" ~ "UDYZ",
                      trasa == "PRG" ~"LKPR",
                      trasa == "Szczytno" ~ "EPSY",
                      trasa == "Przasnysz" ~ "PL-0055",
                      trasa == "Kołobrzeg" ~"PL-0002",
                      trasa == "Akwizgran" ~"EDKA",
                      trasa == "Sandomierz" ~ "NA",
                      trasa == "KTW" ~ "EPKT",
                      trasa == "GDN" ~ "EPGD",
                      trasa == "SZZ" ~"EPSC",
                      trasa == "RZE" ~"EPRZ",
                      trasa == "WRO" ~ "EPWR",
                      trasa == "VRN" ~ "LIPX",
                      trasa == "BRU" ~ "EBBR",
                      trasa == "TLV" ~"LLBG",
                      trasa == "OSL"~"ENGM",
                      trasa == "KRK"~"EPKK",
                      trasa == "MAD"~"LEMD",
                      trasa == "KIV"~"LUKK",
                      trasa == "CDG"~"LFPG",
                      trasa == "VIE"~"LOWW",
                      trasa == "BTS"~"LZIB",
                      trasa == "SXB"~"LFST",
                      trasa == "LCJ"~"EPLL",
                      trasa == "PMO"~"LICJ",
                      trasa == "MRS"~"LFML",
                      trasa == "CPH"~"EKCH",
                      trasa == "EPKT (Muchowiec)" ~"EPKT",
                      trasa == "LCA"~"LCLK",
                      trasa == "RLG"~"ETNL",
                      trasa == "OTP"~"LROP",
                      trasa == "KBP"~"UKBB",
                      trasa == "DBV"~"LDDU",
                      trasa == "ZHR"~"LDDU",
                      trasa == "HEL"~"EFHK",
                      trasa == "HAJ"~"EDDV",
                      trasa == "IEG"~"EPZG",
                      trasa == "POZ"~"EPPO",
                      trasa == "TLL"~"EETN",
                      trasa == "DUB"~"EIDW",
                      trasa == "RIX"~"EVRA",
                      trasa == "GLS"~"KGLS",
                      trasa == "LBG"~"LFPB",
                      trasa == "STN"~"EGSS",
                      trasa == "TXL"~"EDDT",
                      trasa == "CIA"~"LIRA",
                      trasa == "IST"~"TR-0043",
                      trasa == "ULN"~"ZMUB",
                      trasa == "SCV"~"LRSV",
                      trasa == "LTN"~"EGGW",
                      trasa == "TIA"~"LATI",
                      trasa == "MLA"~"LMML",
                      trasa == "RTM"~"EHRD",
                      trasa == "SOF"~"LBSF",
                      trasa == "GOT"~"ESGG",
                      trasa == "BZG"~"EPBY",
                      trasa == "CMN"~"GMMN",
                      trasa == "TUN"~"DTTA",
                      trasa == "ZRH"~"LSZH",
                      trasa == "SZY"~"EPSY",
                      trasa == "BEY"~"OLBA",
                      trasa == "MUC"~"EDDM",
                      trasa == "VNO"~"SA32",
                      trasa == "PLQ"~"EYPA",
                      trasa == "WMI"~"EPMO",
                      trasa == "KLV"~"LKKV",
                      trasa == "LNZ"~"LOWL",
                      trasa == "HAM"~"EDDH",
                      trasa == "SQQ"~"EYSA",
                      trasa == "SBZ"~"LRSB",
                      trasa == "SOU"~"EGHI",
                      trasa == "DRS"~"EDDC",
                      trasa == "Dubrovnik" ~ "LDDU",
                      trasa == "Mirosławiec" ~ "EPMI",
                      trasa == "Świnoujście" ~"EDAH",
                      trasa == "Grajewo" ~ "EPWA",
                      trasa == "Zambrów" ~"EPWA",
                      trasa == "Warna" ~ "LBWN",
                      trasa == "Tarnów" ~"PL-0122",
                      trasa == "Kaniów" ~ "EPKW",
                      trasa == "Michałków" ~ "EPOM",
                      trasa == "Suszno" ~ "EPLS",
                      trasa == "Ankara" ~ "LTAC",
                      trasa == "Torrejon" ~"LETO",
                      trasa == "Stambuł" ~ "LTBA",
                      trasa == "Dubrownik" ~ "LDDU",
                      trasa == "Podgorica" ~ "LYPG",
                      trasa == "InoWRO" ~ "EPIN",
                      trasa == "Włocławek" ~ "EPWK",
                      trasa == "Mielnik" ~ "NA",
                      trasa == "Bielsk Podl" ~ "NA",
                      trasa == "Stębark" ~ "SZY",
                      trasa == "CISNA" ~"EPWA",
                      trasa == "Białystok" ~ "EPBK",
                      trasa == "Siemirowice" ~ "NA",
                      trasa == "Łososina" ~ "EPNL",
                      trasa == "" ~ "NA",
                      trasa == "Nowy Sącz" ~ "EPNL",
                      trasa == "Cieszyn" ~ "EPKT",
                      trasa == "Zagrzeb" ~ "LDZA",
                      trasa == "Lubliniec" ~ "NA",
                      trasa == "Ziemsko" ~ "EPDR",
                      trasa == "Luksemburg" ~ "ELLX",
                      trasa == "Talli" ~ "EETN",
                      trasa == "Poprad" ~"LZTT",
                      trasa == "Lizbona" ~ "LPPT",
                      trasa == "Belgrad" ~ "LYBE",
                      trasa == "Madryt" ~ "LEMD",
                      trasa == "Mińsk Maz." ~ "EPMM",
                      trasa == "Wadowice" ~ "NA",
                      trasa == "Busko Zdrój" ~ "EPKK",
                      trasa == "Krynica" ~ "NA",
                      trasa == "Oxfordshire" ~ "EGTK",
                      trasa == "Sztokholm" ~ "ESSA",
                      trasa == "Opole" ~ "EPOP",
                      trasa == "Zakopane" ~ "LZTT",
                      trasa == "Bartoszyce" ~ "EPSY",
                      trasa == "Neapol" ~ "LIRN",
                      trasa == "Kartrijk" ~ "EBKT",
                      trasa == "Ostrowiec Św" ~ "EPMO",
                      trasa == "Mediolan" ~ "LIMC",
                      trasa == "Kortrijk" ~ "EBKT",
                      trasa == "Bolonia" ~ "LIPE",
                      trasa == "Bogatynia" ~ "NA",
                      trasa == "Warka" ~ "NA",
                      trasa == "Jurata" ~ "EPGD",
                      trasa == "Kłoszko (JW.)" ~ "NA",
                      trasa == "Ostróda" ~ "EPGD",
                      trasa == "Białystok (aeroklub)" ~ "EPBK",
                      trasa == "Huwniki" ~ "NA",
                      trasa == "Nadroże" ~ "NA",
                      
                            TRUE ~ trasa)) 
```

```{r}
df_v2 <- df_v1 %>% 
  mutate(trasa = str_split(trasa, pattern = " |/")) %>% 
  unnest() %>% 
  mutate(
    trasa = str_trim(trasa, side = "both"),
    trasa = case_when(trasa == "Rzym" ~ "LIRF",
                           trasa == "Berlin" ~ "EDDT",
                           trasa == "Paryż" ~ "LFPG",
                           trasa == "Bruksela" ~ "EBBR",
                           trasa == "Irak"~ "ORBI",
                           trasa == "Moskwa" ~ "UUEE",
                           trasa == "Świdwin" ~ "EPSE",
                           trasa == "Kijów" ~ "UKBB",
                           trasa == "Lima" ~ "SPIM",
                           trasa == "Santiago de Chile" ~ "SCEL",
                           trasa == "Nowy Targ" ~ "EPNT",
                           trasa == "Gołdap" ~"EPWA",
                           trasa == "Krynica (Krzyżówka)" ~ "EPGD",
                           trasa == "Sztokcholm" ~ "ESSA",
                      trasa == "Strzelce Op." ~ "EPOP",
                      trasa == "Sewilla"~ "LEZL",
                      trasa == "WAW" ~ "EPWA",
                      trasa == "Szanghaj" ~ "ZSPD",
                      trasa == "Pekin" ~ "ZBAA",
                      trasa == "Frankfurt" ~ "EDDF",
                      trasa == "Kuwejt" ~ "OKBK",
                      trasa == "Londyn" ~ "EGLL",
                      trasa == "Radzikowo" ~ "EPSK",
                      trasa == "Werona" ~ "LIPX",
                      trasa == "Bratysława" ~ "LZIB",
                      trasa == "Zurich" ~ "LSZH",
                      trasa == "Monachium" ~ "EDDM",
                      trasa == "Hamburg" ~ "EDDH",
                      trasa == "Radom" ~ "EPRA",
                      trasa == "Olecko" ~ "EPSY",
                      trasa == "Praga" ~ "LKPR",
                      trasa == "Tallin" ~ "EETN",
                      trasa == "Helsinki" ~ "EFHK",
                      trasa == "Kazimierz Biskupi" ~ "EPKB",
                      trasa == "Poniatowa" ~ "LUZ",
                      trasa == "Turbia" ~ "EPST",
                      trasa == "Rzeszów" ~ "EPRZ",
                      trasa == "Pomysk Wlk." ~ "NA",
                      trasa == "Osnabruck" ~ "EDWO",
                      trasa == "Jarocin" ~ "NA",
                      trasa == "Eindhoven" ~ "EHEH",
                      trasa == "Valetta" ~"LMML",
                      trasa == "Ateny" ~ "LGAV",
                      trasa == "Kolonia" ~ "EDDK",
                      trasa == "Kopenhaga" ~ "EKCH",
                      trasa == "Orzysz" ~ "PL-0058",
                      trasa == "Oświęcim" ~"EPKK",
                      trasa == "BUD" ~"LHBP",
                      trasa == "Gdynia" ~ "EPOK",
                      trasa == "Tbilisi" ~ "UGTB",
                      trasa == "Smoleńsk" ~ "RU-4069",
                      trasa == "Erewań" ~ "UDYZ",
                      trasa == "PRG" ~"LKPR",
                      trasa == "Szczytno" ~ "EPSY",
                      trasa == "Przasnysz" ~ "PL-0055",
                      trasa == "Kołobrzeg" ~"PL-0002",
                      trasa == "Akwizgran" ~"EDKA",
                      trasa == "Sandomierz" ~ "NA",
                      trasa == "KTW" ~ "EPKT",
                      trasa == "GDN" ~ "EPGD",
                      trasa == "SZZ" ~"EPSC",
                      trasa == "RZE" ~"EPRZ",
                      trasa == "WRO" ~ "EPWR",
                      trasa == "VRN" ~ "LIPX",
                      trasa == "BRU" ~ "EBBR",
                      trasa == "TLV" ~"LLBG",
                      trasa == "OSL"~"ENGM",
                      trasa == "KRK"~"EPKK",
                      trasa == "MAD"~"LEMD",
                      trasa == "KIV"~"LUKK",
                      trasa == "CDG"~"LFPG",
                      trasa == "VIE"~"LOWW",
                      trasa == "BTS"~"LZIB",
                      trasa == "SXB"~"LFST",
                      trasa == "LCJ"~"EPLL",
                      trasa == "PMO"~"LICJ",
                      trasa == "MRS"~"LFML",
                      trasa == "CPH"~"EKCH",
                      trasa == "EPKT (Muchowiec)" ~"EPKT",
                      trasa == "LCA"~"LCLK",
                      trasa == "RLG"~"ETNL",
                      trasa == "OTP"~"LROP",
                      trasa == "KBP"~"UKBB",
                      trasa == "DBV"~"LDDU",
                      trasa == "ZHR"~"LDDU",
                      trasa == "HEL"~"EFHK",
                      trasa == "HAJ"~"EDDV",
                      trasa == "IEG"~"EPZG",
                      trasa == "POZ"~"EPPO",
                      trasa == "TLL"~"EETN",
                      trasa == "DUB"~"EIDW",
                      trasa == "RIX"~"EVRA",
                      trasa == "GLS"~"KGLS",
                      trasa == "LBG"~"LFPB",
                      trasa == "STN"~"EGSS",
                      trasa == "TXL"~"EDDT",
                      trasa == "CIA"~"LIRA",
                      trasa == "IST"~"TR-0043",
                      trasa == "ULN"~"ZMUB",
                      trasa == "SCV"~"LRSV",
                      trasa == "LTN"~"EGGW",
                      trasa == "TIA"~"LATI",
                      trasa == "MLA"~"LMML",
                      trasa == "RTM"~"EHRD",
                      trasa == "SOF"~"LBSF",
                      trasa == "GOT"~"ESGG",
                      trasa == "BZG"~"EPBY",
                      trasa == "CMN"~"GMMN",
                      trasa == "TUN"~"DTTA",
                      trasa == "ZRH"~"LSZH",
                      trasa == "SZY"~"EPSY",
                      trasa == "BEY"~"OLBA",
                      trasa == "MUC"~"EDDM",
                      trasa == "VNO"~"SA32",
                      trasa == "PLQ"~"EYPA",
                      trasa == "WMI"~"EPMO",
                      trasa == "KLV"~"LKKV",
                      trasa == "LNZ"~"LOWL",
                      trasa == "HAM"~"EDDH",
                      trasa == "SQQ"~"EYSA",
                      trasa == "SBZ"~"LRSB",
                      trasa == "SOU"~"EGHI",
                      trasa == "DRS"~"EDDC",
                      trasa == "Dubrovnik" ~ "LDDU",
                      trasa == "Mirosławiec" ~ "EPMI",
                      trasa == "Świnoujście" ~"EDAH",
                      trasa == "Grajewo" ~ "EPWA",
                      trasa == "Zambrów" ~"EPWA",
                      trasa == "Warna" ~ "LBWN",
                      trasa == "Tarnów" ~"PL-0122",
                      trasa == "Kaniów" ~ "EPKW",
                      trasa == "Michałków" ~ "EPOM",
                      trasa == "Suszno" ~ "EPLS",
                      trasa == "Ankara" ~ "LTAC",
                      trasa == "Torrejon" ~"LETO",
                      trasa == "Stambuł" ~ "LTBA",
                      trasa == "Dubrownik" ~ "LDDU",
                      trasa == "Podgorica" ~ "LYPG",
                      trasa == "InoWRO" ~ "EPIN",
                      trasa == "Włocławek" ~ "EPWK",
                      trasa == "Mielnik" ~ "NA",
                      trasa == "Bielsk Podl" ~ "NA",
                      trasa == "Stębark" ~ "SZY",
                      trasa == "CISNA" ~"EPWA",
                      trasa == "Białystok" ~ "EPBK",
                      trasa == "Siemirowice" ~ "NA",
                      trasa == "Łososina" ~ "EPNL",
                      trasa == "" ~ "NA",
                      trasa == "Nowy Sącz" ~ "EPNL",
                      trasa == "Cieszyn" ~ "EPKT",
                      trasa == "Zagrzeb" ~ "LDZA",
                      trasa == "Lubliniec" ~ "NA",
                      trasa == "Ziemsko" ~ "EPDR",
                      trasa == "Luksemburg" ~ "ELLX",
                      trasa == "Talli" ~ "EETN",
                      trasa == "Poprad" ~"LZTT",
                      trasa == "Lizbona" ~ "LPPT",
                      trasa == "Belgrad" ~ "LYBE",
                      trasa == "Madryt" ~ "LEMD",
                      trasa == "Mińsk Maz." ~ "EPMM",
                      trasa == "Wadowice" ~ "NA",
                      trasa == "Busko Zdrój" ~ "EPKK",
                      trasa == "Krynica" ~ "NA",
                      trasa == "Oxfordshire" ~ "EGTK",
                      trasa == "Sztokholm" ~ "ESSA",
                      trasa == "Opole" ~ "EPOP",
                      trasa == "Zakopane" ~ "LZTT",
                      trasa == "Bartoszyce" ~ "EPSY",
                      trasa == "Neapol" ~ "LIRN",
                      trasa == "Kartrijk" ~ "EBKT",
                      trasa == "Ostrowiec Św" ~ "EPMO",
                      trasa == "Mediolan" ~ "LIMC",
                      trasa == "Kortrijk" ~ "EBKT",
                      trasa == "Bolonia" ~ "LIPE",
                      trasa == "Bogatynia" ~ "NA",
                      trasa == "Warka" ~ "NA",
                      trasa == "Jurata" ~ "EPGD",
                      trasa == "Kłoszko (JW.)" ~ "NA",
                      trasa == "Ostróda" ~ "EPGD",
                      trasa == "Białystok (aeroklub)" ~ "EPBK",
                      trasa == "Huwniki" ~ "NA",
                      trasa == "Nadroże" ~ "NA",
                      trasa == "Waw" ~ "EPWA",
                      trasa == "Zawada" ~"NA",
                      trasa == "Radwan" ~ "NA",
                      trasa == "Dziewiętlice" ~ "EPWR",
                      trasa == "Wrocław" ~ "EPWR",
                      trasa == "Dubaj" ~"OMDB",
                      trasa == "AUH" ~ "OMAA",
                      trasa == "RUH" ~ "OERK",
                      trasa == "Kłodzko" ~ "NA", 
                      trasa == "(JW.)" ~ "NA",
                      trasa == "Łódź" ~ "EPLL",
                      trasa == "Łyse" ~ "NA",
                      trasa == "Baku" ~ "UBBB",
                            TRUE ~ trasa)) %>% 
  filter(trasa != "NA")
  
```

