---
title: "NLP"
author: "Igor Adamiec"
date: "1/11/2019"
output: html_document
---

```{r}
library(tidyverse)
library(tm)
```

```{r}
dataset <- read_tsv("Restaurant_Reviews.tsv")
```

```{r}
glimpse(dataset)
```

```{r}
corpus <- VCorpus(VectorSource(dataset$Review))
```

```{r}
corpus <- tm_map(corpus, content_transformer(tolower))
```

```{r}
corpus <- tm_map(corpus, removeNumbers)
```

```{r}
corpus <- tm_map(corpus, removePunctuation)
```

```{r}
library(SnowballC)
corpus <- tm_map(corpus, removeWords, stopwords())
```

```{r}
corpus <- tm_map(corpus, stemDocument)
```

```{r}
corpus <- tm_map(corpus, stripWhitespace)
```

```{r}
dtm <- DocumentTermMatrix(corpus)
```

```{r}
dtm <- removeSparseTerms(dtm, .999)#we wan to keep 99.9% of most frequent words
```

```{r}
df <- as.data.frame(as.matrix(dtm))
df$Liked <- dataset$Liked
```

```{r}
df <- df %>% 
  mutate(Liked = factor(Liked, levels = c(0, 1)))
```

```{r}
library(caTools)
set.seed(123)
split <- sample.split(df$Liked, SplitRatio = .8)
training_set <- subset(df, split == T)
test_set <- subset(df, split == F)
```

```{r}
library(randomForest)
classifier <- randomForest(x = training_set %>% select(-Liked),
                           y = training_set$Liked,
                           ntree = 10)
```

```{r}
y_pred <- predict(classifier, newdata = test_set %>% select(-Liked))
```

```{r}
cm <- table(y_pred, test_set %>% pull(Liked))
cm
```

```{r}
#accuracy
(82+77)/200
```




















