---
title: "Random Forest"
author: "Igor Adamiec"
date: "1/3/2019"
output: html_document
---

```{r}
library(tidyverse)
library(caTools)
library(randomForest)
```

```{r}
dataset <- read_csv("Social_Network_Ads.csv") %>% 
  select(Age:Purchased) %>% 
  mutate(Purchased = factor(Purchased, 
                            levels = c(0, 1))) %>% 
  mutate_if(is.integer, scale) %>% 
  mutate_if(is.matrix, as.vector)
head(dataset)
```
```{r}
dataset %>% glimpse
```

```{r}
dataset %>% summary
```

```{r}
set.seed(123)
split <- sample.split(dataset %>% pull(Purchased), 
                      SplitRatio = .75)
training_set <- dataset %>% 
  subset(split == T)
test_set <- dataset %>% 
  subset(split == F)
```

```{r}
training_set %>% summary
```

```{r}
test_set %>% summary
```

```{r}
classifier <- randomForest(x = training_set %>% select(Age, EstimatedSalary),
                           y = training_set %>% pull(Purchased),
                           ntree = 10)
```

```{r}
y_pred <- predict(classifier, 
                  newdata = test_set %>% select(-Purchased))
```

```{r}
cm <- table(test_set %>% pull(Purchased), y_pred)
cm
```

```{r}
set <- training_set
X1 <- seq(min(set[, 1]) -1, max(set[, 1]) + 1, by = .01)
X2 <- seq(min(set[, 2]) -1, max(set[, 2]) + 1, by = .01)
grid_set <- expand.grid(X1, X2)
colnames(grid_set) <- c("Age", "EstimatedSalary")
y_grid <- predict(classifier, newdata = grid_set)
ggplot()+
  geom_point(data = grid_set, aes(x = Age, y = EstimatedSalary), color = ifelse(y_grid == 1, 'springgreen3', 'tomato'))+
  geom_point(data = set, aes(x = Age, y = EstimatedSalary), pch = 21, fill = ifelse(set$Purchased == 1,  'green4', 'red3'), color = "black")+
  labs(title = "Training Data Random Forest") +
  theme(plot.title = element_text(hjust = .5))
```

```{r}
set <- test_set
X1 <- seq(min(set[, 1]) -1, max(set[, 1]) + 1, by = .01)
X2 <- seq(min(set[, 2]) -1, max(set[, 2]) + 1, by = .01)
grid_set <- expand.grid(X1, X2)
colnames(grid_set) <- c("Age", "EstimatedSalary")
y_grid <- predict(classifier, newdata = grid_set)
ggplot()+
  geom_point(data = grid_set, aes(x = Age, y = EstimatedSalary), color = ifelse(y_grid == 1, 'springgreen3', 'tomato'))+
  geom_point(data = set, aes(x = Age, y = EstimatedSalary), pch = 21, fill = ifelse(set$Purchased == 1,  'green4', 'red3'), color = "black")+
  labs(title = "Test Data Random Forest") +
  theme(plot.title = element_text(hjust = .5))
```